#baseURL = "http://example.org/"
#languageCode = "en-us"
#title = "My New Hugo Site"
#theme = "ananke"

baseurl = "http://www.spargonaut.com" # Hostname (and path) to the root.
title = "home" # Site title.
theme = "coder" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

#disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "spargonaut" # Author's name.
    info = "Full Stack DevOps and Magician" # Author's job title or info.
    description = "John Doe's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "images/spargonaut_icon.jpg" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "you do you" # Add footer content

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css =[ "styles/spargonaut-styles.css" ]

    # RTL support
    rtl = false

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "i code"
    weight = 1
    url = "https://github.com/spargonaut/"
[[params.social]]
    name = "i tweet"
    weight = 2
    url = "https://twitter.com/spargonaut/"
[[params.social]]
    name = "i do"
    weight = 3
    url = "https://www.linkedin.com/in/johndoe/"

# Menu links
[[menu.main]]
    name = "blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "projects"
    weight = 2
    url = "/projects/"
