#baseURL = "http://example.org/"
#languageCode = "en-us"
#title = "My New Hugo Site"
#theme = "ananke"

baseurl = "https://www.spargonaut.com" # Hostname (and path) to the root.
title = "home" # Site title.
theme = "coder" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

#disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "spargonaut" # Author's name.
    info = "working really hard" # Author's job title or info.
    description = "james spargo's personal website" # Site description.
    keywords = "blog,developer,personal,spargonaut,fossflight,sinsi,android" # Site keywords.
    avatarurl = "images/spargonaut_icon.jpg" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "to be incredibly lazy" # Add footer content

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true

    # Custom CSS
    custom_css = [ "styles/spargonaut-styles.css" ]

    # RTL support
    rtl = false

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Menu links
[[menu.main]]
    name = "blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "projects"
    weight = 2
    url = "/projects/"
