pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                checkout scmGit(
                    branches: [[name: 'main']],
                    userRemoteConfigs: [[credentialsId:  'build-monkey-key',
                   url: 'develop:/repos/spargonaut.com.git']])

               sh(script: '''
                    git config user.email "jenkins@spargonaut.com"
                    git config user.name "Build Monkey"
                    cd spargonaut-www
                    make gen-wtf
                ''',
                returnStdout: true)

               sh(script: 'git status', returnStdout: true)

            }
        }

        stage('Deploy') {
            steps {
                sshagent(credentials: ['deploy-monkey-key']) {

                    sh '''
                        cd spargonaut-www/public
                        ls -lR
                        scp -rp ./* ${DEPLOYMENT_USER}@${DEPLOYMENT_SERVER}:~/spargonaut.wtf/html
                    '''
                }
            }
        }
    }
}